cargo-features = ["trim-paths"]

[package]
name = "tar-xz-wasm"
edition = "2024"
license = "LicenseRef-File-to-Downloader"
publish = false

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }

missing_errors_doc = "allow"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
console_error_panic_hook = "0.1"
js-sys = "0.3"
leptos = { version = "0.8", features = ["csr"] }
leptos-use = { version = "0.19", default-features = false, features = ["use_document"] }
lzma-rust2 = { version = "0.16", default-features = false, features = ["encoder", "optimization", "std", "xz"] }
obfstr = "0.4"
tar = "0.4"
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = [
	"Blob",
	"BlobPropertyBag",
	"Document",
	"Element",
	"HtmlAnchorElement",
	"HtmlElement",
	"Url"
] }

[profile.release]
opt-level = "z"
strip = "symbols"
overflow-checks = false
lto = "fat"
codegen-units = 1

trim-paths = "all"

[profile.dev]
opt-level = 1
debug = "line-tables-only"
incremental = true

trim-paths = "all"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O4", "--all-features"]