name: Deploy tar.xz

on:
  push:
    branches: [fyl]
  pull_request:
    branches: [fyl]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: tar.xz-deployer
  cancel-in-progress: true

jobs:
  deploy-tar_xz:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git config --global core.quotePath false
          git config --global core.ignorecase false
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: |
          rustup default nightly
          rustup target add wasm32-unknown-unknown
          rustup component add rust-src
          rustup update
          cargo install wasm-pack
          bun i
          bun run build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: tar.xz-dist
          folder: dist
          clean: true
          single-commit: true